### ISSUE TITLE
contact --> mailto vdog8122@gmail.com

### ISSUE THREAD

**Issue by chiaochiao123** [chiaochiao123/chiaochiao123.github.io#6]
## Navbar 的 Contact 連結使用 `mailto` 即可
contact --> mailto vdog8122@gmail.com

**Comment by lizwang50** [comment]
@chiaochiao123 你 Contact 連結信箱要不要跳出去另外一個視窗？

**Comment by lizwang50** [comment]
@chiaochiao123 這條我做好惹
